# Specify the nodes to setup. You can add more or remove entries, as you wish.

# 12/2020 - This gets installed in /etc/ansible/hosts once ansible is installed. (mfreeman@blackshakes.net)


# ## Validator 0
[validator-0]
51.222.105.172

[validator-0:vars]
ansible_user=ansible
# Preferably use a private telemetry server
telemetryUrl=wss://telemetry.blackshakes.net/submit/
loggingFilter='sync=warn,afg=warn,babe=warn'


# ## Validator 1
[validator-1]
51.178.91.111

[validator-1:vars]
ansible_user=ansible
# Preferably use a private telemetry server
telemetryUrl=wss://telemetry.blackshakes.net/submit/
loggingFilter='sync=warn,afg=warn,babe=warn'

# ## Validator 2
[validator-2]
51.89.172.3

[validator-:vars]
ansible_user=ansible
# Preferably use a private telemetry server
telemetryUrl=wss://telemetry.blackshakes.net/submit/
loggingFilter='sync=warn,afg=warn,babe=warn'

# ## Group all nodes
[validator:children]
validator-0
validator-1
validator-2


# ## Common variables
[all:vars]
# The name for how each node should be prefixed for the telemetry name
project=blackshakes

# Can be left as is.
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ConnectTimeout=15'
build_dir=$HOME/.config/polkadot-secure-validator/build/w3f/ansible

# Specify which `polkadot` binary to install. Checksum is verified during execution.
# v0.8.26-1
#polkadot_binary_url='https://github.com/paritytech/polkadot/releases/download/v0.8.2/polkadot'
polkadot_binary_url='https://github.com/paritytech/polkadot/releases/download/v0.8.26-1/polkadot'
#polkadot_binary_checksum='sha256:349b786476de9188b79817cab48fc6fc030908ac0e8e2a46a1600625b1990758'
polkadot_binary_checksum='sha256:edd811ccd884e5997493b346d1e8f660414193e0fd55e8fdfc59c8f967644ce6'

# Specify the chain/network.
#
# For Polkadot:
# ```
# chain=polkadot
# polkadot_network_id=polkadot
# ```
#
# For Kusama:
# ```
# chain=kusama
# polkadot_network_id=ksmcc3
# ```
polkadot_network_id=polkadot
chain=polkadot

# Node exporter settings. Disabled by default.
node_exporter_enabled='true'
node_exporter_user='admin'
node_exporter_password='Bl4ckSh4k3z{2020}!'
node_exporter_binary_url='https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz'
node_exporter_binary_checksum='sha256:3369b76cd2b0ba678b6d618deab320e565c3d93ccb5c2a0d5db51a53857768ae'

# Polkadot service restart settings. Enabled to restart every hour.
polkadot_restart_enabled='true'
polkadot_restart_minute='0'
polkadot_restart_hour='*'
polkadot_restart_day='*'
polkadot_restart_month='*'
polkadot_restart_weekday='*'
